### ISSUE TITLE
rgb_to_hex.py _ Incorrect variables

### ISSUE THREAD

**Issue by JVT135** [tsruth/CS120-Open-Source#11]
# Issue/Bug Report
**Description**
Variables are named incorrectly

**Steps to Reproduce**
1. First step to reproduce the issue/bug
2. Second step to reproduce the issue/bug
3. Third step to reproduce the issue/bug

**Expected Behavior**

**Actual Behavior**
A clear and concise description of what actually happened.

**Screenshots**
If applicable, add screenshots to help explain the issue/bug.

**Additional Information**
* Operating System:
* Browser:
* Version:
* Any other relevant information

**Possible Solution**
fix the variable names when initialized and when passed to the function.

**Related Issues**
Are there any related issues? If so, please link to them here.

**Priority**
How critical is this issue/bug? Low, medium, or high priority?

**Reproducibility**
How often can this issue/bug be reproduced? Always, sometimes, or random?

**Impact**
What is the impact of this issue/bug? Low, medium, or high?

**Comment by tsruth** [comment]
changed variable R to lowercase
