### ISSUE TITLE
datetime_convert.cc

### ISSUE THREAD

**Issue by tsruth** [tsruth/CS120-Open-Source#14]
ISSUE REPORT

Reproduction:
When running the code there is a compiler error and the build fails. The project does not compile.

Expected Behavior:
It is expected that this project will run and generate html code for even and odd numbers

Screenshots:
<img width="843" alt="Screenshot 2023-03-21 at 5 21 47 PM" src="https://user-images.githubusercontent.com/95494504/226743680-c6eb08bf-8746-4b59-b122-97778267b80a.png">

Additional Info:
OS: MacOS Ventura 13.0
Browser: Safari

Possible Solution: Add semicolon where needed

Priority:
Critical

Reproducibility:
Very easy

Impact:
High

**Comment by BMWolf57** [comment]
Added a semicolon on line 10 and fixed the bug
