### ISSUE TITLE
removed_duplicates iterator bug

### ISSUE THREAD

**Issue by BMWolf57** [tsruth/CS120-Open-Source#15]
Everytime you run the loop it skips over some of the indexes. 
1. run program with multiple things
2. see that it skips over certain indexes
it should be doing every index but it does not
possible solution - get rid of the iterator in one of the statements
priority - medium
reproducibility - add lots of numbers into the list
impact - medium

**Comment by tsruth** [comment]
Removed the second iterator ("++i;") on line 20
