### ISSUE TITLE
datetime_convert.cc

### ISSUE THREAD

**Issue by tsruth** [tsruth/CS120-Open-Source#16]
ISSUE REPORT

Reproduction:
When running the code there is a compiler error and the build fails. The project does not compile. Undeclared identifier "ss"

Expected Behavior:
It is expected that this project will run and generate html code for even and odd numbers

Screenshots:

Additional Info:
OS: MacOS Ventura 13.0
Browser: Safari

Possible Solution: Add "std::" to the beginning of string stream declaration

Priority:
Critical

Reproducibility:
Very easy

Impact:
High

**Comment by BMWolf57** [comment]
Bug solved, added in the std:: on line 11 where the error occurred.
