### ISSUE TITLE
rgb_to_hex.java - incorrect variables

### ISSUE THREAD

**Issue by JVT135** [tsruth/CS120-Open-Source#9]
# Issue/Bug Report
**Names for integers are incorrect and are passed incorrectly to the functions**
A clear and concise description of what the issue/bug is.

**Steps to Reproduce**
1. Run the file

**Expected Behavior**
The program to run

**Actual Behavior**
The program did not run

**Screenshots**
If applicable, add screenshots to help explain the issue/bug.

**Additional Information**
* Operating System:
* Browser:
* Version:
* Any other relevant information

**Possible Solution**
Name the variables correctly

**Related Issues**
Are there any related issues? If so, please link to them here.

**Priority**
High priority

**Reproducibility**
Always

**Impact**
High priority

**Comment by tsruth** [comment]
changed variable in 'format(r, g, g)' to 'format(r, g, b)'
